// docs/src/pages/_app.tsx
import '@docsearch/css';
import {
  HydrationBoundary,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query';
import { SearchProvider } from '@/components/useSearch';
import { useState } from 'react';
import '@/styles/index.css';
import { AppProps } from 'next/app';

export default function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <HydrationBoundary state={pageProps.dehydratedState}>
        <SearchProvider>
          <Component {...pageProps} />
        </SearchProvider>
      </HydrationBoundary>
    </QueryClientProvider>
  );
}

// samples/solid-query/custom-fetch/src/App.tsx
import type { Component } from 'solid-js';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import Pets from './lib/Pets';
import './App.css';

const queryClient = new QueryClient();

const App: Component = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <main>
        <h1>Vite + Solid with fetch API</h1>
        <Pets />
      </main>
    </QueryClientProvider>
  );
};

export default App;
