// samples/nx-fastify-react/apps/app/src/app/app.tsx
import React, { useEffect } from 'react';
import { useGetPets } from '../api/endpoints/petstoreAPI';
import { Container } from './app.style';
import logo from './logo.svg';

function App() {
  const { data: pets, refetch } = useGetPets();

  useEffect(() => {
    setTimeout(() => {
      refetch();
    }, 2000);
  }, [refetch]);

  return (
    <Container>
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        {pets?.map((pet) => <p key={pet.id}>{pet.name}</p>)}
      </header>
    </Container>
  );
}

export default App;

// samples/angular-query/src/app/app.ts
import { Component, signal } from '@angular/core';
import { injectListPets } from '../api/endpoints/pets/pets';

@Component({
  selector: 'app-root',
  template: `
    <div class="App">
      <h1>Hello, {{ title() }}</h1>
      <header class="App-header">
        <img src="logo.svg" class="App-logo" alt="logo" />
        @for (pet of pets.data(); track pet.id) {
          <p>{{ pet.name }}</p>
        }
      </header>
    </div>
  `,
})
export class App {
  protected readonly pets = injectListPets();

  protected readonly title = signal('angular-app');
}
