// samples/nx-fastify-react/apps/app/src/app/app.tsx
import React, { useEffect } from 'react';
import { useGetPets } from '../api/endpoints/petstoreAPI';
import { Container } from './app.style';
import logo from './logo.svg';

function App() {
  const { data: pets, refetch } = useGetPets();

  useEffect(() => {
    setTimeout(() => {
      refetch();
    }, 2000);
  }, [refetch]);

  return (
    <Container>
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        {pets?.map((pet) => <p key={pet.id}>{pet.name}</p>)}
      </header>
    </Container>
  );
}

export default App;

// samples/angular-app/src/app/app.ts
import { Component, inject } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { PetsService } from '../api/endpoints/pets/pets.service';

@Component({
  selector: 'app-root',
  imports: [AsyncPipe],
  template: `
    <div class="App">
      <header class="App-header">
        <img src="logo.svg" class="App-logo" alt="logo" />
        @for (pet of pets$ | async; track pet) {
          <p>{{ pet.name }}</p>
        }
      </header>
    </div>
  `,
})
export class App {
  private readonly petService = inject(PetsService);
  protected readonly pets$ = this.petService.listPets();
}
