// samples/react-app-with-react-query/src/App.tsx
import React from 'react';
import { useListPets } from './api/endpoints/petstoreFromFileSpecWithTransformer';
import './App.css';
import logo from './logo.png';

function App() {
  const { data: pets } = useListPets();

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        {pets?.map((pet: any) => (
          <p key={pet.id}>{pet.name}</p>
        ))}
      </header>
    </div>
  );
}

export default App;

// samples/angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { PetsApiService } from '../api/endpoints/pets/pets.service';
import { Pet } from '../api/model';

@Component({
  selector: 'app-root',
  template: `
    <div className="App">
      <header className="App-header">
        <img src="../assets/logo.png" className="App-logo" alt="logo" />
        <p *ngFor="let pet of pets$ | async">{{ pet.name }}</p>
      </header>
    </div>
  `,
})
export class AppComponent implements OnInit {
  pets$: Observable<Pet[]>;
  constructor(private readonly petsApiService: PetsApiService) {}

  ngOnInit() {
    this.pets$ = this.petsApiService.listPets();
  }
}
