// samples/vue-query/src/components/pets.vue
<template>
  <p v-for="pet in pets" :key="pet.id">{{ pet.name }}</p>
</template>

<script lang="ts">
import { useListPets } from '../api/endpoints/petstoreFromFileSpecWithTransformer';

export default {
  name: 'Pets',
  setup() {
    const { data } = useListPets();
    return {
      pets: data,
    };
  },
};
</script>

// samples/svelte-query/basic/src/lib/pets.svelte
<script lang="ts">
  import {createListPets} from '../api/endpoints/petstoreFromFileSpecWithTransformer';

  const pets = createListPets();
</script>

<main class="App">
    <header class="App-header">
        <img src="/logo.svg" class="App-logo" alt="logo"/>
        {#if $pets.isLoading}
            <span>Loading...</span>
        {:else if $pets.isError}
            <span>Error: {$pets.error}</span>
        {:else}
            <ul>
                {#each $pets.data as pet (pet.id)}
                    <li>{pet.name}</li>
                {/each}
            </ul>
        {/if}
    </header>
</main>
