// samples/solid-query/custom-fetch/src/App.tsx
import type { Component } from 'solid-js';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import Pets from './lib/Pets';
import './App.css';

const queryClient = new QueryClient();

const App: Component = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <main>
        <h1>Vite + Solid with fetch API</h1>
        <Pets />
      </main>
    </QueryClientProvider>
  );
};

export default App;

// samples/react-query/custom-fetch/src/App.tsx
import './App.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import Pets from './pets';

function App() {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <div>
        <Pets />
      </div>
    </QueryClientProvider>
  );
}

export default App;
