// samples/solid-query/custom-fetch/src/lib/Pets.tsx
import { Component, For, Show } from 'solid-js';

import { useListPets, useCreatePets } from '../gen/pets/pets';

const Pets: Component = () => {
  const queryResult = useListPets();
  const mutation = useCreatePets();

  const handleCreate = () => {
    mutation.mutate({ data: [{ name: 'New Pet', tag: 'test' }] });
  };

  return (
    <div>
      <h2>Pets</h2>
      <Show when={queryResult.data}>
        <ul>
          <For each={queryResult.data!.data}>
            {(pet) => <li>{pet.name}</li>}
          </For>
        </ul>

        <button onClick={handleCreate} disabled={mutation.isPending}>
          {mutation.isPending ? 'Creating...' : 'Create Pet'}
        </button>

        <Show when={mutation.isError}>
          <p style="color: red">Error: {mutation.error?.message}</p>
        </Show>

        <Show when={mutation.isSuccess}>
          <p style="color: green">Pet created successfully!</p>
        </Show>
      </Show>
    </div>
  );
};

export default Pets;

// samples/svelte-query/v6-custom-fetch/src/lib/Pets.svelte
<script lang="ts">
  import { createListPets, createCreatePets } from "../gen/pets/pets";

  const queryResult = createListPets(() => ({ limit: "10" }), () => ({ query: { staleTime: 10000 } }));
  const mutation = createCreatePets();
  
</script>

<h2>Pets</h2>

{#if queryResult.isSuccess}
  <ul>
    {#each queryResult.data.data as pet}
      <li>{pet.name}</li>
    {/each}
  </ul>

  <button
    on:click={() => {
      mutation.mutate({ data: [{ name: 'testName', tag: 'testTag' }]})
    }}>
    Create
  </button>
{/if}
