// samples/react-query/custom-fetch/src/pets.tsx
import { useListPets, useCreatePets } from './gen/pets/pets';
import { Pet } from './gen/models';

export default function Pets() {
  const { data } = useListPets();
  const mutation = useCreatePets();

  return (
    <div>
      <h1 className="text-4xl">Pets by react-query</h1>

      <ul>
        {data && data.data.map((pet: Pet) => <li key={pet.id}>{pet.name}</li>)}
      </ul>

      <button
        onClick={() =>
          mutation.mutate({ data: [{ name: 'testName', tag: 'testTag' }] })
        }
      >
        Create a pet
      </button>
    </div>
  );
}

// samples/svelte-query/v6-custom-fetch/src/lib/Pets.svelte
<script lang="ts">
  import { createListPets, createCreatePets } from "../gen/pets/pets";

  const queryResult = createListPets(() => ({ limit: "10" }), () => ({ query: { staleTime: 10000 } }));
  const mutation = createCreatePets();
  
</script>

<h2>Pets</h2>

{#if queryResult.isSuccess}
  <ul>
    {#each queryResult.data.data as pet}
      <li>{pet.name}</li>
    {/each}
  </ul>

  <button
    on:click={() => {
      mutation.mutate({ data: [{ name: 'testName', tag: 'testTag' }]})
    }}>
    Create
  </button>
{/if}
