// samples/react-app/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from 'react-query';
import App from './App';
import { AuthProvider } from './auth.context';
import './index.css';

const queryClient = new QueryClient();

const enableMocking = async () => {
  if (import.meta.env.DEV) {
    const { setupWorker } = await import('msw/browser');
    const { getSwaggerPetstoreMock } =
      await import('./api/endpoints/petstoreFromFileSpecWithTransformer.msw');
    const worker = setupWorker(...getSwaggerPetstoreMock());
    await worker.start();
  }
};

enableMocking().then(() => {
  ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
      <AuthProvider>
        <QueryClientProvider client={queryClient}>
          <App />
        </QueryClientProvider>
      </AuthProvider>
    </React.StrictMode>,
  );
});

// samples/solid-query/basic/src/index.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
/* @refresh reload */
import { render } from 'solid-js/web';

import App from './App';
import './index.css';

const queryClient = new QueryClient();

const root = document.getElementById('root');

async function startApp() {
  if (import.meta.env.DEV) {
    const { initMocks } = await import('./mocks');
    await initMocks();
    // Give MSW a moment to fully activate the service worker
    await new Promise((resolve) => setTimeout(resolve, 100));
    console.log('✅ Mocks initialized and ready, rendering app...');
  }

  render(
    () => (
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    ),
    root!,
  );
}

startApp();
