// samples/solid-query/custom-fetch/src/App.tsx
import type { Component } from 'solid-js';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import Pets from './lib/Pets';
import './App.css';

const queryClient = new QueryClient();

const App: Component = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <main>
        <h1>Vite + Solid with fetch API</h1>
        <Pets />
      </main>
    </QueryClientProvider>
  );
};

export default App;

// samples/svelte-query/custom-fetch/src/App.svelte
<script lang="ts">
  import Pets from './lib/Pets.svelte';

  import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query'

  const queryClient = new QueryClient()
</script>

<main>
  <QueryClientProvider client={queryClient}>
    <h1>Vite + Svelte with fetch api</h1>
    
    <Pets />    
  </QueryClientProvider>
</main>
