// samples/next-app-with-fetch/app/pets.tsx
import { listPets } from './gen/pets/pets';

export default async function Pets() {
  const { data: pets, status } = await listPets();

  return (
    <div>
      <h1 className="text-4xl">Pets by server actions</h1>

      <ul>
        {pets.map((pet) => (
          <li key={pet.id}>{pet.name}</li>
        ))}
      </ul>

      <h2 className="text-xl">Status: {status}</h2>
    </div>
  );
}

// samples/vue-query/src/components/pets.vue
<template>
  <p v-for="pet in pets" :key="pet.id">{{ pet.name }}</p>
</template>

<script lang="ts">
import { useListPets } from '../api/endpoints/petstoreFromFileSpecWithTransformer';

export default {
  name: 'Pets',
  setup() {
    const { data } = useListPets();
    return {
      pets: data,
    };
  },
};
</script>
